service: alexa-starling-bank

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  memorySize: 128
  environment:
    STARLING_ACCESS_TOKEN: ${env:STARLING_ACCESS_TOKEN}

functions:
  handler:
    handler: handler.handler
    events:
      - alexaSkill