version: 2
jobs:
    build:
        working_directory: /alexa-starling-bank
        docker:
            - image: node:7.7.2
        steps:
            - checkout
            - run:
                name: 'Dependencies'
                command: 'yarn'
            - run:
                name: 'Unit tests'
                command: './node_modules/.bin/jest'
            - run:
                name: 'Lint'
                command: ./node_modules/.bin/eslint --quiet .